=== zycgit/dbvisitor/dbvisitor/src/main/resources/net/hasor/dbvisitor/dal/repository/parser/dbvisitor-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
       Copyright 2015-2022 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.
-->
<!ELEMENT mapper ( resultMap* | entity* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
        namespace CDATA #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT resultMap (result*)>
<!ATTLIST resultMap
        type CDATA #REQUIRED
        id CDATA #IMPLIED
        catalog CDATA #IMPLIED
        schema CDATA #IMPLIED
        table CDATA #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT result EMPTY>
<!ATTLIST result
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        >

<!ELEMENT entity (id*,mapping*)>
<!ATTLIST entity
        type CDATA #REQUIRED
        id CDATA #IMPLIED
        catalog CDATA #IMPLIED
        schema CDATA #IMPLIED
        table CDATA #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT id EMPTY>
<!ATTLIST id
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setColTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        >

<!ELEMENT mapping EMPTY>
<!ATTLIST mapping
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setColTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        >

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT update (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST selectKey
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        resultType CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType CDATA #IMPLIED
        keyProperty CDATA #REQUIRED
        keyColumn CDATA #IMPLIED
        order (BEFORE|AFTER) #IMPLIED
        handler CDATA #IMPLIED
        >

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        resultMap CDATA #IMPLIED
        resultType CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
        multipleResult (FIRST|LAST|ALL) #IMPLIED
        >

<!-- Dynamic -->
<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
        id CDATA #REQUIRED
        >

<!ELEMENT include EMPTY>
<!ATTLIST include
        refid CDATA #REQUIRED
        >

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
        prefix CDATA #IMPLIED
        prefixOverrides CDATA #IMPLIED
        suffix CDATA #IMPLIED
        suffixOverrides CDATA #IMPLIED
        >

<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
        collection CDATA #REQUIRED
        item CDATA #REQUIRED
        index CDATA #IMPLIED
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        separator CDATA #IMPLIED
        >

<!ELEMENT choose (when* , otherwise?)>

<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
        test CDATA #REQUIRED
        >

<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
        test CDATA #REQUIRED
        >

<!ELEMENT bind EMPTY>
<!ATTLIST bind
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

=== zycgit/dbvisitor/dbvisitor/src/test/resources/dbvisitor_scene/mongodb/user-mapper-5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.scene.mongodb.dto5.UserInfo5Mapper">
    <resultMap id="userResultMap" type="net.hasor.scene.mongodb.dto5.UserInfo5">
        <result column="uid" property="userId"/>
        <result column="name" property="userName"/>
        <result column="loginName" property="account"/>
        <result column="loginPassword" property="password"/>
    </resultMap>

    <insert id="saveUser">
        test.user_info.insert({
            uid: #{info.userId},
            name: #{info.userName},
            loginName: #{info.account},
            loginPassword: #{info.password}
        })
    </insert>

    <select id="loadUser" resultMap="userResultMap">
        test.user_info.find({uid: #{userId}})
    </select>

    <delete id="deleteUser">
        test.user_info.remove({uid: #{userId}})
    </delete>
</mapper>

=== zycgit/dbvisitor/dbvisitor/src/test/resources/dbvisitor_coverage/dal_mapping/mapper_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="resultMap_test">
    <resultMap id="resultMap_1" type="net.hasor.test.entity.BlobResourceV1"/>
    <resultMap id="resultMap_2" type="net.hasor.test.entity.BlobResourceV2"/>
    <resultMap id="resultMap_3" type="net.hasor.test.entity.BlobResourceV3"/>
    <resultMap id="resultMap_4" type="net.hasor.test.entity.BlobResourceV4"/>
    <resultMap id="resultMap_5" type="net.hasor.test.entity.BlobResourceV5"/>
    <resultMap id="resultMap_6" type="net.hasor.test.entity2.BlobResourceV6"/>
    <resultMap id="resultMap_7" type="net.hasor.test.entity2.BlobResourceV7"/>
    <resultMap id="resultMap_8" type="net.hasor.test.entity2.BlobResourceV8"/>
    <resultMap id="resultMap_9" type="net.hasor.test.entity2.BlobResourceV9"/>
    <resultMap id="resultMap_10" type="net.hasor.test.entity2.BlobResourceV10"/>

    <entity id="entityMap_1" type="net.hasor.test.entity.BlobResourceV1"/>
    <entity id="entityMap_2" type="net.hasor.test.entity.BlobResourceV2"/>
    <entity id="entityMap_3" type="net.hasor.test.entity.BlobResourceV3"/>
    <entity id="entityMap_4" type="net.hasor.test.entity.BlobResourceV4"/>
    <entity id="entityMap_5" table="blob_resource" type="net.hasor.test.entity.BlobResourceV5"/>
    <entity id="entityMap_6" type="net.hasor.test.entity2.BlobResourceV6"/>
    <entity id="entityMap_7" type="net.hasor.test.entity2.BlobResourceV7"/>
    <entity id="entityMap_8" type="net.hasor.test.entity2.BlobResourceV8"/>
    <entity id="entityMap_9" type="net.hasor.test.entity2.BlobResourceV9"/>
    <entity id="entityMap_10" table="blob_resource" type="net.hasor.test.entity2.BlobResourceV10"/>

    <resultMap id="repeat_1" type="net.hasor.test.entity2.BlobResourceV9"/>
</mapper>

=== zycgit/dbvisitor/dbvisitor/src/test/resources/dbvisitor_coverage/dal_repository/autoMapping_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper>
    <resultMap id="resultMap_1" type="net.hasor.test.dto.user_info"/>

    <resultMap id="resultMap_2" type="net.hasor.test.dto.UserInfo2"/>

    <resultMap id="resultMap_3" type="net.hasor.test.dto.UserInfo">
        <result column="user_uuid" property="userUuid"/>
        <result column="user_name" property="name"/>
        <result column="login_name" property="loginName"/>
        <result column="login_password" property="loginPassword"/>
        <result column="email" property="email"/>
        <result column="seq" property="seq" javaType="java.lang.Integer"/>
        <result column="register_time" property="registerTime"/>
    </resultMap>

    <resultMap id="resultMap_4" type="net.hasor.test.dto.UserInfo" mapUnderscoreToCamelCase="true"/>
</mapper>

=== zycgit/dbvisitor/dbvisitor/src/test/resources/dbvisitor_coverage/basic_mapper/basic_xml_dynamic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.dbvisitor.mapper.dto.DynamicXmlMapper">
    <resultMap id="userInfo" type="net.hasor.dbvisitor.mapper.dto.UserInfo" autoMapping="true"/>

    <sql id="alertConfigDetail_allColumns">
        *
    </sql>
    <sql id="projectInfoDO_allColumns">
        *
    </sql>
    <sql id="user_do_allColumns">
        name,login_name
    </sql>

    <select id="bind_01">
        <bind name="abc" value="sellerId + 'abc'"/>
        select * from console_job where aac = #{abc}
    </select>

    <select id="choose_01">
        select * from t_blog
        <where>
            <choose>
                <when test="title != null">and title = #{title}</when>
                <when test="content != null">and content = #{content}</when>
                <otherwise>and owner = "owner1"</otherwise>
            </choose>
        </where>
    </select>

    <select id="foreach_03">
        SELECT
            <include refid="alertConfigDetail_allColumns"/>
        FROM
            alert_detail
        WHERE
            alert_detail.event_type IN
            <foreach collection="resTypes" item="regType" separator="," open="(" close=")">
                #{regType,javaType=net.hasor.dbvisitor.mapper.dto.ResourceType}
            </foreach>
    </select>

    <select id="if_01">
        select
        <include refid="projectInfoDO_allColumns"/>
        from
            PROJECT_INFO
        where 1=1
            and status = 2
            <if test="ownerID != null and ownerType !=null">
                and owner_id = #{ownerID}
                and owner_type = #{ownerType}
            </if>
        order by
            name asc
    </select>

    <select id="include_01">
        SELECT
            <include refid="alertConfigDetail_allColumns"/>
        FROM
            alert_detail
        WHERE
            event_type = #{eventType,javaType=java.lang.Integer}
    </select>

    <insert id="selectKey_01">
        insert into test_user (
            <include refid="user_do_allColumns"/>
        ) values (
            #{user.name} , #{user.loginName}
        );
        <selectKey keyProperty="id" order="AFTER" resultType="java.lang.Integer">
            SELECT LAST_INSERT_ID()
        </selectKey>
    </insert>

    <update id="set_04">
        UPDATE
            alert_users
        <set>
            <if test="user.name != null">
                name = #{user.name},
            </if>
            <if test="user.loginName != null">
                loginName = #{user.loginName},
            </if>
            <if test="user.email != null">
                email = #{user.email},
            </if>
            <if test="user.seq != null">
                seq = #{user.seq},
            </if>
        </set>
        WHERE uid = #{user.userUuid}
    </update>

    <select id="where_01">
        SELECT * FROM BLOG
        <where>
            <if test="name != null">
                and name = #{name}
            </if>
            <if test="loginName != null">
                and login_name like #{loginName}
            </if>
        </where>
    </select>
</mapper>

=== zycgit/dbvisitor/dbvisitor/src/test/resources/dbvisitor_coverage/dal_repository/mapper_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper autoMapping="true">
    <resultMap id="mapper_2" type="net.hasor.test.dto.UserInfo2"/>

    <resultMap id="mapper_3" type="net.hasor.test.dto.UserInfo"/>

    <resultMap id="mapper_4" type="net.hasor.test.dto.UserInfo" autoMapping="false">
        <result column="user_uuid" property="userUuid"/>
        <result column="name" property="name"/>
        <result column="login_name" property="loginName"/>
        <result column="login_password" property="loginPassword"/>
        <result column="email" property="email"/>
        <result column="index" property="seq" javaType="int"/>
        <result column="register_time" property="registerTime"/>
    </resultMap>

    <resultMap id="mapper_5" type="net.hasor.test.dto.UserInfo" mapUnderscoreToCamelCase="true"/>
</mapper>

=== zycgit/dbvisitor/dbvisitor/src/test/resources/dbvisitor_coverage/dal_dynamic/mapper/mapper_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.dal.mapper_3">

    <resultMap id="tb_user_resultMap" type="net.hasor.test.dto.TbUser2">
        <id column="user_uuid" property="uid"/>
        <result column="name" property="name"/>
        <result column="login_name" property="account"/>
        <result column="login_password" property="password"/>
        <result column="email" property="mail"/>
        <result column="index" property="index" javaType="int"/>
        <result column="register_time" property="createTime"/>
    </resultMap>

    <sql id="projectInfoDO_allColumns">
        id, owner_id
    </sql>

    <!-- dataqlMap="tb_user_dataqlMap"-->
    <select id="testBind" resultMap="tb_user_resultMap">
        SELECT
        <include refid="projectInfoDO_allColumns"/>
        FROM console_job
        WHERE aac = #{abc}
    </select>

    <insert id="testInsert">
        insert into auto_id (
            userUUID, name
        ) values (
            #{uid}, #{name}
        );
        <selectKey keyProperty="id" order="AFTER" resultType="java.lang.Integer">
            SELECT LAST_INSERT_ID()
        </selectKey>
    </insert>
</mapper>

=== zycgit/dbvisitor/dbvisitor/src/test/resources/dbvisitor_coverage/dal_session/page_execute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.dal.execute.PageExecuteDal">

    <entity table="test_user" type="net.hasor.test.dto.TbUser2">
        <id column="user_uuid" property="uid"/>
        <result column="name" property="name"/>
        <result column="login_name" property="account"/>
        <result column="login_password" property="password"/>
        <result column="email" property="mail"/>
        <result column="index" property="index" javaType="int"/>
        <result column="register_time" property="createTime"/>
    </entity>

    <resultMap id="tb_user_resultMap" type="net.hasor.test.dto.TbUser2">
        <id column="user_uuid" property="uid"/>
        <result column="name" property="name"/>
        <result column="login_name" property="account"/>
        <result column="login_password" property="password"/>
        <result column="email" property="mail"/>
        <result column="index" property="index" javaType="int"/>
        <result column="register_time" property="createTime"/>
    </resultMap>

    <sql id="user_do_allColumns">
        user_uuid,
        name,
        login_name,
        login_password,
        email,
        `index`,
        register_time
    </sql>

    <delete id="deleteAll">
        delete from test_user;
    </delete>

    <insert id="createUser">
        insert into test_user (
            <include refid="user_do_allColumns"/>
        ) values (
            #{uid},
            #{name},
            #{account},
            #{password},
            #{email},
            #{index},
            #{createTime}
        )
    </insert>

    <select id="listByPage1" resultMap="tb_user_resultMap" statementType="PREPARED">
        select
            <include refid="user_do_allColumns"/>
        from
            test_user
        where
            name like concat('%', #{name} ,'%')
        order by `index`
    </select>

    <select id="listByPage2" resultMap="tb_user_resultMap" statementType="PREPARED">
        select
            <include refid="user_do_allColumns"/>
        from
            test_user
        where
            name like concat('%', #{name} ,'%')
        order by `index`
    </select>
</mapper>

=== zycgit/dbvisitor/dbvisitor/src/test/resources/dbvisitor_coverage/dal_session/basic_execute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.dal.execute.TestExecuteDal">
    <resultMap id="tb_user_resultMap" type="net.hasor.test.dto.UserInfo">
        <result column="user_uuid" property="userUuid"/>
        <result column="user_name" property="name"/>
        <result column="login_name" property="loginName"/>
        <result column="login_password" property="loginPassword"/>
        <result column="email" property="email"/>
        <result column="seq" property="seq" javaType="int"/>
        <result column="register_time" property="registerTime"/>
    </resultMap>

    <sql id="user_do_allColumns">
        user_uuid,
        user_name,
        login_name,
        login_password,
        email,
        seq,
        register_time
    </sql>

    <insert id="createUser">
        insert into user_info (
            <include refid="user_do_allColumns"/>
        ) values (
            #{userUuid},
            #{name},
            #{loginName},
            #{loginPassword},
            #{email},
            #{seq},
            #{registerTime}
        );
    </insert>

    <insert id="initUser">
        insert into user_info (
            <include refid="user_do_allColumns"/>
        )
        values
        ('11', '12', '13', '14', '15', 16, '2021-07-20 00:00:00'),
        ('21', '22', '23', '24', '25', 26, '2021-07-20 00:00:00')
    </insert>

    <select id="listUserList_1" resultMap="tb_user_resultMap" statementType="PREPARED">
        select
            <include refid="user_do_allColumns"/>
        from
            user_info;
    </select>

    <select id="listUserList_2" resultType="net.hasor.test.dto.UserInfo2" statementType="STATEMENT">
        select
            <include refid="user_do_allColumns"/>
        from
            user_info;
    </select>

    <select id="callSelectUser" statementType="CALLABLE">
        {call proc_select_user(#{abc, mode=out})}
    </select>

    <insert id="insertAutoID_1">
        insert into auto_id (
            uid, name
        ) values (
            #{uid}, #{name}
        );
        <selectKey keyProperty="id" order="AFTER" resultType="java.lang.Integer">
            SELECT LAST_INSERT_ID()
        </selectKey>
    </insert>

    <insert id="insertAutoID_2">
        insert into auto_id (
            uid, name
        ) values (
            #{uid}, #{name}
        );
        <selectKey keyProperty="id" keyColumn="cc" order="AFTER">
            SELECT LAST_INSERT_ID() as cc
        </selectKey>
    </insert>
</mapper>
