=== zycgit/dbvisitor/dbvisitor-doc/static/schema/dbvisitor-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
       Copyright 2015-2022 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.
-->
<!ELEMENT mapper ( resultMap* | entity* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
        namespace CDATA #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        >

<!ELEMENT resultMap (result*)>
<!ATTLIST resultMap
        id CDATA #IMPLIED
        type CDATA #REQUIRED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT result EMPTY>
<!ATTLIST result
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        >

<!ELEMENT entity (id*,mapping*,index*)>
<!ATTLIST entity
        id CDATA #IMPLIED
        catalog CDATA #IMPLIED
        schema CDATA #IMPLIED
        table CDATA #IMPLIED
        type CDATA #REQUIRED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        ddlAuto (none|create|add|update|create-drop) #IMPLIED
        >

<!ELEMENT id EMPTY>
<!ATTLIST id
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setColTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT mapping EMPTY>
<!ATTLIST mapping
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setColTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        nullable (true|false) #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT index (column* | EMPTY)>
<!ATTLIST index
        name CDATA #REQUIRED
        columns CDATA #IMPLIED
        unique (true|false) #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT column (#PCDATA)>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        useGeneratedKeys CDATA #IMPLIED
        keyProperty CDATA #IMPLIED
        parameterType CDATA #IMPLIED
        >

<!ELEMENT update (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST selectKey
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        resultType CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType CDATA #IMPLIED
        keyProperty CDATA #REQUIRED
        keyColumn CDATA #IMPLIED
        order (BEFORE|AFTER) #IMPLIED
        handler CDATA #IMPLIED
        >

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        resultMap CDATA #IMPLIED
        resultType CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
        multipleResult (FIRST|LAST|ALL) #IMPLIED
        >

<!-- Dynamic -->
<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
        id CDATA #REQUIRED
        >

<!ELEMENT include EMPTY>
<!ATTLIST include
        refid CDATA #REQUIRED
        >

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
        prefix CDATA #IMPLIED
        prefixOverrides CDATA #IMPLIED
        suffix CDATA #IMPLIED
        suffixOverrides CDATA #IMPLIED
        >

<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
        collection CDATA #REQUIRED
        item CDATA #REQUIRED
        index CDATA #IMPLIED
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        separator CDATA #IMPLIED
        >

<!ELEMENT choose (when* , otherwise?)>

<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
        test CDATA #REQUIRED
        >

<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
        test CDATA #REQUIRED
        >

<!ELEMENT bind EMPTY>
<!ATTLIST bind
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/oneapi/mapper/KeyTypeMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="KeyTypeMapper">
    
    <!-- ========== Entity 配置示例 ========== -->
    
    <!-- 使用 keyType="auto" 的 entity -->
    <entity id="AutoKeyEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="auto" />
        <mapping column="name" property="name" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 使用 keyType="uuid32" 的 entity -->
    <entity id="Uuid32KeyEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="auto" />
        <mapping column="name" property="name" keyType="uuid32" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 使用 keyType="uuid36" 的 entity -->
    <entity id="Uuid36KeyEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="auto" />
        <mapping column="name" property="name" keyType="uuid36" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 使用 keyType="Sequence::seq_name" 的 entity -->
    <entity id="SequenceKeyEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="Sequence::user_id_seq" />
        <mapping column="name" property="name" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 使用 keyType="完整类名" 的 entity（自定义 Holder） -->
    <entity id="CustomHolderEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="net.hasor.dbvisitor.test.oneapi.handler.keygen.FixedValueKeyHolder" />
        <mapping column="name" property="name" keyType="uuid36" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 多个字段配置不同 keyType -->
    <entity id="MultiKeyTypesEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="auto" />
        <mapping column="name" property="name" keyType="uuid32" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- ========== ResultMap 配置示例 ========== -->
    
    <!-- ResultMap 中 <id> 标签配置 keyType -->
    <resultMap id="UserResultMapWithKeyType" type="map">
        <id column="id" property="id" keyType="auto" />
        <result column="name" property="name" />
        <result column="age" property="age" />
        <result column="create_time" property="createTime" />
    </resultMap>
    
    <!-- ResultMap 中 <result> 标签配置 keyType -->
    <resultMap id="UserResultMapMappingKeyType" type="map">
        <id column="id" property="id" keyType="auto" />
        <result column="name" property="name" keyType="uuid36" />
        <result column="age" property="age" />
        <result column="create_time" property="createTime" />
    </resultMap>
    
    <!-- ========== Insert 语句 ========== -->
    
    <insert id="insertAutoKeyUser" useGeneratedKeys="true" keyProperty="id">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertUuid32User">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertUuid36User">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertSequenceUser" useGeneratedKeys="true" keyProperty="id">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertCustomHolderUser">
        INSERT INTO user_info (id, name, age, create_time)
        VALUES (#{id}, #{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertWithResultMap" resultMap="UserResultMapWithKeyType" useGeneratedKeys="true" keyProperty="id">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertWithMappingKeyType" resultMap="UserResultMapMappingKeyType" useGeneratedKeys="true" keyProperty="id">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertMultiKeyTypes">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <!-- DDL Auto 示例（需要 <entity> 的 ddlAuto 属性支持） -->
    <!-- 注意：这是示例，实际需要在 entity 中配置 ddlAuto="create" -->
    <insert id="insertDdlAutoUser">
        INSERT INTO auto_created_table (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <!-- 错误测试：无效的 keyType -->
    <insert id="insertInvalidKeyType">
        <!-- 这里故意配置无效的 keyType 用于测试错误处理 -->
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <!-- 错误测试：不存在的 Holder 类 -->
    <insert id="insertNonExistentHolder">
        <!-- keyType 配置了不存在的类名 -->
        INSERT INTO user_info (id, name, age, create_time)
        VALUES (#{id}, #{name}, #{age}, #{createTime})
    </insert>
    
</mapper>

=== zycgit/dbvisitor/dbvisitor-core/src/test/resources/net_hasor_db/dal_dynamic/execute/basic_execute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.db.dal.execute.TestExecuteDal">
    <resultMap id="tb_user_resultMap" type="net.hasor.test.db.dto.TbUser2">
        <id column="user_uuid" property="uid"/>
        <result column="name" property="name"/>
        <result column="login_name" property="account"/>
        <result column="login_password" property="password"/>
        <result column="email" property="mail"/>
        <result column="index" property="index" javaType="int"/>
        <result column="register_time" property="createTime"/>
    </resultMap>

    <sql id="user_do_allColumns">
        user_uuid,
        name,
        login_name,
        login_password,
        email,
        `index`,
        register_time
    </sql>

    <insert id="createUser">
        insert into test_user (
        <include refid="user_do_allColumns"/>
        ) values (
        #{uid},
        #{name},
        #{account},
        #{password},
        #{index},
        #{createTime}
        );
    </insert>

    <insert id="initUser">
        insert into test_user (
        <include refid="user_do_allColumns"/>
        )
        values ('11', '12', '13', '14', '15', 16, '2021-07-20 00:00:00'),
        ('21', '22', '23', '24', '25', 26, '2021-07-20 00:00:00');
    </insert>

    <select id="listUserList_1"  resultMap="tb_user_resultMap" statementType="PREPARED">
        select
        <include refid="user_do_allColumns"/>
        from test_user;
    </select>

    <select id="listUserList_2" resultType="net.hasor.test.db.dal.execute.TestUser" statementType="STATEMENT">
        select
        <include refid="user_do_allColumns"/>
        from test_user;
    </select>

    <select id="callSelectUser" statementType="CALLABLE">
        {call proc_select_user(#{abc, mode=out})}
    </select>

    <insert id="insertAutoID_1">
        insert into auto_id (
            userUUID, name
        ) values (
            #{uid}, #{name}
        );
        <selectKey keyProperty="id" order="AFTER" resultType="java.lang.Integer">
            SELECT LAST_INSERT_ID()
        </selectKey>
    </insert>

    <insert id="insertAutoID_2">
        insert into auto_id (
            userUUID, name
        ) values (
            #{uid}, #{name}
        );
        <selectKey keyProperty="id" keyColumn="cc" order="AFTER">
            SELECT LAST_INSERT_ID() as cc
        </selectKey>
    </insert>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/oneapi/session/UserSessionMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="oneapi.session.UserSessionMapper">

    <resultMap id="userInfoMap" type="net.hasor.dbvisitor.test.oneapi.model.UserInfo">
        <result column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <resultMap id="orderMap" type="net.hasor.dbvisitor.test.oneapi.model.UserOrder">
        <result column="id" property="id"/>
        <result column="user_id" property="userId"/>
        <result column="order_no" property="orderNo"/>
        <result column="amount" property="amount"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <resultMap id="orderDtoMap" type="net.hasor.dbvisitor.test.oneapi.model.UserOrderDTO">
        <result column="order_id" property="orderId"/>
        <result column="order_no" property="orderNo"/>
        <result column="amount" property="amount"/>
        <result column="create_time" property="createTime"/>
        <result column="user_id" property="userId"/>
        <result column="user_name" property="userName"/>
        <result column="user_email" property="userEmail"/>
    </resultMap>

    <!-- ========== user_info CRUD ========== -->

    <insert id="insertUser">
        insert into user_info (id, name, age, email, create_time)
        values (#{id}, #{name}, #{age}, #{email}, CURRENT_TIMESTAMP)
    </insert>

    <select id="queryUserById" resultMap="userInfoMap">
        select * from user_info where id = #{id}
    </select>

    <select id="queryAllUsers" resultMap="userInfoMap">
        select * from user_info order by id asc
    </select>

    <select id="queryUsersByAge" resultMap="userInfoMap">
        select * from user_info where age = #{age} order by id asc
    </select>

    <select id="countUsers" resultType="int">
        select count(*) from user_info
    </select>

    <update id="updateUserEmail">
        update user_info set email = #{email} where id = #{id}
    </update>

    <delete id="deleteUserById">
        delete from user_info where id = #{id}
    </delete>

    <!-- ========== user_order CRUD ========== -->

    <insert id="insertOrder">
        insert into user_order (id, user_id, order_no, amount, create_time)
        values (#{id}, #{userId}, #{orderNo}, #{amount}, CURRENT_TIMESTAMP)
    </insert>

    <select id="queryOrdersByUserId" resultMap="orderMap">
        select * from user_order where user_id = #{userId} order by id asc
    </select>

    <delete id="deleteOrderById">
        delete from user_order where id = #{id}
    </delete>

    <!-- ========== JOIN 查询 ========== -->

    <select id="queryOrderWithUser" resultMap="orderDtoMap">
        select o.id as order_id, o.order_no, o.amount, o.create_time,
               u.id as user_id, u.name as user_name, u.email as user_email
        from user_order o
        left join user_info u on o.user_id = u.id
        where o.id = #{orderId}
    </select>

    <!-- ========== 动态条件查询 ========== -->

    <select id="queryUsersByCondition" resultMap="userInfoMap">
        select * from user_info
        where 1=1
        @{and, name = :name}
        @{and, age = :age}
        order by id asc
    </select>

    <!-- ========== Bean 参数 ========== -->

    <select id="queryUserByBean" resultMap="userInfoMap">
        select * from user_info where name = #{name} and age = #{age}
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapping/basic_entity_mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.mapping">

    <!-- 基本 entity 测试: 完整属性配置 -->
    <entity id="FullEntity" table="user_info" type="net.hasor.dbvisitor.test.model.UserInfo"
            catalog="test_cat" schema="test_sch"
            ddlAuto="create" character-set="utf8mb4" collation="utf8mb4_general_ci"
            comment="user table" other="ENGINE=InnoDB">
        <id column="id" property="id" keyType="auto"/>
        <mapping column="name" property="name"/>
        <mapping column="age" property="age" insert="false"/>
        <mapping column="email" property="email" update="false"/>
        <mapping column="create_time" property="createTime"/>
        <index name="idx_name" columns="name"/>
        <index name="idx_email_age" columns="email,age" unique="true" comment="composite index"/>
    </entity>

    <!-- 基本 resultMap 测试 -->
    <resultMap id="SimpleResultMap" type="net.hasor.dbvisitor.test.model.UserInfo">
        <result column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <!-- autoMapping=false, 只映射部分列 -->
    <entity id="PartialEntity" table="user_info" type="net.hasor.dbvisitor.test.model.UserInfo"
            autoMapping="false">
        <id column="id" property="id"/>
        <mapping column="name" property="name"/>
    </entity>

    <!-- 使用 column description 属性 -->
    <entity id="DescEntity" table="user_info" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id" sqlType="BIGINT"/>
        <mapping column="name" property="name" sqlType="VARCHAR" length="128" default="'unknown'" comment="user name"/>
        <mapping column="age" property="age" precision="10" scale="0"/>
    </entity>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/XmlJoinQueryMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.JoinQueryMapper">

    <resultMap id="userOrderDTOMap" type="net.hasor.dbvisitor.test.model.UserOrderDTO">
        <result column="order_id" property="orderId"/>
        <result column="order_no" property="orderNo"/>
        <result column="amount" property="amount"/>
        <result column="order_create_time" property="createTime"/>
        <result column="user_id" property="userId"/>
        <result column="user_name" property="userName"/>
        <result column="user_email" property="userEmail"/>
    </resultMap>

    <insert id="insertUser">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, CURRENT_TIMESTAMP)
    </insert>

    <insert id="insertOrder">
        INSERT INTO user_order (id, user_id, order_no, amount, create_time)
        VALUES (#{id}, #{userId}, #{orderNo}, #{amount}, CURRENT_TIMESTAMP)
    </insert>

    <!-- INNER JOIN：映射到 DTO -->
    <select id="selectUserOrderDTO" resultMap="userOrderDTOMap">
        SELECT
            o.id AS order_id,
            o.order_no AS order_no,
            o.amount AS amount,
            o.create_time AS order_create_time,
            u.id AS user_id,
            u.name AS user_name,
            u.email AS user_email
        FROM user_order o
        INNER JOIN user_info u ON o.user_id = u.id
        WHERE u.id = #{userId}
        ORDER BY o.id
    </select>

    <!-- INNER JOIN：映射到 Map -->
    <select id="selectUserOrderMap" resultType="map">
        SELECT
            o.id AS order_id,
            o.order_no,
            o.amount,
            u.id AS user_id,
            u.name AS user_name,
            u.email AS user_email
        FROM user_order o
        INNER JOIN user_info u ON o.user_id = u.id
        WHERE u.id = #{userId}
        ORDER BY o.id
    </select>

    <!-- LEFT JOIN：无匹配行时 null 处理 -->
    <select id="selectUserOrderLeftJoin" resultType="map">
        SELECT
            u.id AS user_id,
            u.name AS user_name,
            o.id AS order_id,
            o.order_no
        FROM user_info u
        LEFT JOIN user_order o ON u.id = o.user_id
        WHERE u.id = #{userId}
    </select>

    <!-- 聚合函数 + GROUP BY -->
    <select id="selectUserOrderAggregate" resultType="map">
        SELECT
            u.id AS user_id,
            u.name AS user_name,
            COUNT(o.id) AS order_count,
            COALESCE(SUM(o.amount), 0) AS total_amount
        FROM user_info u
        LEFT JOIN user_order o ON u.id = o.user_id
        WHERE u.id = #{userId}
        GROUP BY u.id, u.name
    </select>

    <!-- 自连接 -->
    <select id="selectSameAgeUsers" resultType="map">
        SELECT
            u1.id AS user1_id,
            u1.name AS user1_name,
            u2.id AS user2_id,
            u2.name AS user2_name,
            u1.age AS common_age
        FROM user_info u1
        INNER JOIN user_info u2 ON u1.age = u2.age AND u1.id &lt; u2.id
        WHERE u1.name LIKE 'JoinQ%' AND u2.name LIKE 'JoinQ%'
        ORDER BY u1.age, u1.id
    </select>

    <!-- 子查询 -->
    <select id="selectUsersWithOrders" resultType="net.hasor.dbvisitor.test.model.UserInfo">
        SELECT * FROM user_info
        WHERE id IN (
            SELECT DISTINCT user_id FROM user_order
        )
        AND name LIKE 'JoinQ%'
        ORDER BY id
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapping/write_policy_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.xml.writepolicy">

    <!-- insert="false": name 列不参与 INSERT -->
    <entity id="InsertFalseEntity" table="user_info_if" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" insert="false"/>
        <mapping column="age" property="age"/>
    </entity>

    <!-- update="false": name 列不参与 UPDATE -->
    <entity id="UpdateFalseEntity" table="user_info_uf" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" update="false"/>
        <mapping column="age" property="age"/>
    </entity>

    <!-- insert="false" update="false": name 列完全只读 -->
    <entity id="BothFalseEntity" table="user_info_bf" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" insert="false" update="false"/>
        <mapping column="age" property="age"/>
    </entity>

    <!-- 默认策略: 不指定 insert/update → 均为 true -->
    <entity id="DefaultPolicyEntity" table="user_info_dp" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name"/>
        <mapping column="age" property="age"/>
    </entity>

</mapper>

=== zycgit/dbvisitor/dbvisitor-core/src/test/resources/net_hasor_db/dal_repository/mapper_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="resultMap_test">
    <resultMap id="blobResourceDO" type="net.hasor.test.db.dto.TB_User" autoMapping="true">
        <id column="id" property="id"/>
        <result column="gmt_create" property="gmtCreate"/>
        <result column="gmt_modified" property="gmtModified"/>
        <result column="instance_id" property="instanceId"/>
        <result column="owner_name" property="ownerName"/>
        <result column="owner_type" property="ownerType" javaType="com.clougence.clouddm.console.web.constants.ResourceType"/>
        <result column="blob_type" property="blobType" javaType="com.clougence.clouddm.console.web.constants.SecurityFileType"/>
        <result column="content" property="content"/>
    </resultMap>

    <resultMap id="blobResourceDO" type="net.hasor.test.db.dto.TB_User" autoMapping="true">
        <id column="id" property="id"/>
        <result column="gmt_create" property="gmtCreate"/>
        <result column="gmt_modified" property="gmtModified"/>
        <result column="instance_id" property="instanceId"/>
        <result column="owner_name" property="ownerName"/>
        <result column="owner_type" property="ownerType" javaType="com.clougence.clouddm.console.web.constants.ResourceType"/>
        <result column="blob_type" property="blobType" javaType="com.clougence.clouddm.console.web.constants.SecurityFileType"/>
        <result column="content" property="content"/>
    </resultMap>
</mapper>

=== zycgit/dbvisitor/dbvisitor-core/src/test/resources/net_hasor_db/dal_repository/mapper_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper autoMapping="true">
    <resultMap id="mapper_2" type="net.hasor.test.db.dto.TbUser"/>

    <resultMap id="mapper_3" type="net.hasor.test.db.dto.TbUser2"/>

    <resultMap id="mapper_4" type="net.hasor.test.db.dto.TbUser2" autoMapping="false">
        <id column="user_uuid" property="uid"/>
        <result column="name" property="name"/>
        <result column="login_name" property="account"/>
        <result column="login_password" property="password"/>
        <result column="email" property="mail"/>
        <result column="index" property="index" javaType="int"/>
        <result column="register_time" property="createTime"/>
    </resultMap>

    <resultMap id="mapper_5" type="net.hasor.test.db.dto.TbUser2" mapUnderscoreToCamelCase="true"/>
</mapper>
