=== zycgit/dbvisitor/dbvisitor-doc/static/schema/dbvisitor-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
       Copyright 2015-2022 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.
-->
<!ELEMENT mapper ( resultMap* | entity* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
        namespace CDATA #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        >

<!ELEMENT resultMap (result*)>
<!ATTLIST resultMap
        id CDATA #IMPLIED
        type CDATA #REQUIRED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT result EMPTY>
<!ATTLIST result
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        >

<!ELEMENT entity (id*,mapping*,index*)>
<!ATTLIST entity
        id CDATA #IMPLIED
        catalog CDATA #IMPLIED
        schema CDATA #IMPLIED
        table CDATA #IMPLIED
        type CDATA #REQUIRED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        ddlAuto (none|create|add|update|create-drop) #IMPLIED
        >

<!ELEMENT id EMPTY>
<!ATTLIST id
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setColTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT mapping EMPTY>
<!ATTLIST mapping
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setColTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        nullable (true|false) #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT index (column* | EMPTY)>
<!ATTLIST index
        name CDATA #REQUIRED
        columns CDATA #IMPLIED
        unique (true|false) #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT column (#PCDATA)>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        useGeneratedKeys CDATA #IMPLIED
        keyProperty CDATA #IMPLIED
        parameterType CDATA #IMPLIED
        >

<!ELEMENT update (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST selectKey
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        resultType CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType CDATA #IMPLIED
        keyProperty CDATA #REQUIRED
        keyColumn CDATA #IMPLIED
        order (BEFORE|AFTER) #IMPLIED
        handler CDATA #IMPLIED
        >

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        resultMap CDATA #IMPLIED
        resultType CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
        multipleResult (FIRST|LAST|ALL) #IMPLIED
        >

<!-- Dynamic -->
<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
        id CDATA #REQUIRED
        >

<!ELEMENT include EMPTY>
<!ATTLIST include
        refid CDATA #REQUIRED
        >

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
        prefix CDATA #IMPLIED
        prefixOverrides CDATA #IMPLIED
        suffix CDATA #IMPLIED
        suffixOverrides CDATA #IMPLIED
        >

<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
        collection CDATA #REQUIRED
        item CDATA #REQUIRED
        index CDATA #IMPLIED
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        separator CDATA #IMPLIED
        >

<!ELEMENT choose (when* , otherwise?)>

<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
        test CDATA #REQUIRED
        >

<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
        test CDATA #REQUIRED
        >

<!ELEMENT bind EMPTY>
<!ATTLIST bind
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/oneapi/mapping/template_attrs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.xml.template">

    <!-- selectTemplate 和 insertTemplate -->
    <entity id="SelectInsertTemplateEntity" table="user_info_si" type="net.hasor.dbvisitor.test.oneapi.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" selectTemplate="UPPER(name)" insertTemplate="LOWER(?)"/>
    </entity>

    <!-- setValueTemplate 和 whereColTemplate -->
    <entity id="UpdateWhereTemplateEntity" table="user_info_uw" type="net.hasor.dbvisitor.test.oneapi.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" setValueTemplate="TRIM(?)" whereColTemplate="LOWER(name)"/>
    </entity>

    <!-- 所有 5 个 template 属性同时设置在一列上 -->
    <entity id="AllTemplatesEntity" table="user_info_at" type="net.hasor.dbvisitor.test.oneapi.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name"
                 selectTemplate="UPPER(name)"
                 insertTemplate="LOWER(?)"
                 setValueTemplate="TRIM(?)"
                 whereColTemplate="LOWER(name)"
                 whereValueTemplate="LOWER(?)"/>
    </entity>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/oneapi/mapper/XmlStatementAttrMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.StatementAttrMapper">

    <resultMap id="userResultMap" type="net.hasor.dbvisitor.test.oneapi.model.UserInfo">
        <id column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <insert id="insertUser">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, CURRENT_TIMESTAMP)
    </insert>

    <!-- 默认 PREPARED 类型 -->
    <select id="selectPrepared" resultMap="userResultMap">
        SELECT * FROM user_info WHERE id = #{id}
    </select>

    <!-- 显式 PREPARED 类型 -->
    <select id="selectExplicitPrepared" resultMap="userResultMap" statementType="PREPARED">
        SELECT * FROM user_info WHERE id = #{id}
    </select>

    <!-- STATEMENT 类型（非预编译） -->
    <select id="selectStatement" resultMap="userResultMap" statementType="STATEMENT">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- timeout 超时设置 -->
    <select id="selectWithTimeout" resultMap="userResultMap" timeout="30">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- fetchSize 设置 -->
    <select id="selectWithFetchSize" resultMap="userResultMap" fetchSize="5">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- resultSetType 设置 -->
    <select id="selectForwardOnly" resultMap="userResultMap" resultSetType="FORWARD_ONLY">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <select id="selectScrollInsensitive" resultMap="userResultMap" resultSetType="SCROLL_INSENSITIVE">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- 组合属性 -->
    <select id="selectCombined" resultMap="userResultMap"
            statementType="PREPARED" timeout="30" fetchSize="10" resultSetType="FORWARD_ONLY">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- insert 的 statementType（使用默认 PREPARED 但显式标注） -->
    <insert id="insertWithStatement" statementType="PREPARED">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, CURRENT_TIMESTAMP)
    </insert>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/XmlDynamicSqlMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.DynamicSqlMapper">

    <resultMap id="userResultMap" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <insert id="insertUser">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, CURRENT_TIMESTAMP)
    </insert>

    <!-- if 标签测试 -->
    <select id="selectWithIf" resultMap="userResultMap">
        SELECT * FROM user_info
        WHERE name LIKE 'DynSql%'
        <if test="minAge != null">
            AND age &gt;= #{minAge}
        </if>
        <if test="email != null">
            AND email = #{email}
        </if>
        ORDER BY id
    </select>

    <!-- choose/when/otherwise 标签测试 -->
    <select id="selectWithChoose" resultMap="userResultMap">
        SELECT * FROM user_info
        WHERE name LIKE 'DynSql%'
        ORDER BY
        <choose>
            <when test="orderBy == 'name'">
                name ASC
            </when>
            <when test="orderBy == 'age'">
                age DESC
            </when>
            <otherwise>
                id ASC
            </otherwise>
        </choose>
    </select>

    <!-- where 标签测试：自动处理 AND/OR 前缀 -->
    <select id="selectWithWhere" resultMap="userResultMap">
        SELECT * FROM user_info
        <where>
            <if test="name != null">
                AND name = #{name}
            </if>
            <if test="age != null">
                AND age = #{age}
            </if>
            <if test="email != null">
                AND email = #{email}
            </if>
        </where>
        ORDER BY id
    </select>

    <!-- set 标签测试：自动处理尾部逗号 -->
    <update id="updateWithSet">
        UPDATE user_info
        <set>
            <if test="name != null">
                name = #{name},
            </if>
            <if test="age != null">
                age = #{age},
            </if>
            <if test="email != null">
                email = #{email},
            </if>
        </set>
        WHERE id = #{id}
    </update>

    <!-- trim 标签测试 -->
    <select id="selectWithTrim" resultMap="userResultMap">
        SELECT * FROM user_info
        <trim prefix="WHERE" prefixOverrides="AND |OR ">
            <if test="name != null">
                AND name = #{name}
            </if>
            <if test="age != null">
                AND age = #{age}
            </if>
        </trim>
        ORDER BY id
    </select>

    <!-- foreach 标签测试：IN 子句 -->
    <select id="selectByIdList" resultMap="userResultMap">
        SELECT * FROM user_info
        WHERE id IN
        <foreach collection="ids" item="id" open="(" separator="," close=")">
            #{id}
        </foreach>
        ORDER BY id
    </select>

    <!-- foreach 标签测试：批量 VALUES 插入 -->
    <insert id="batchInsert">
        INSERT INTO user_info (id, name, age, email, create_time) VALUES
        <foreach collection="users" item="u" separator=",">
            (#{u.id}, #{u.name}, #{u.age}, #{u.email}, CURRENT_TIMESTAMP)
        </foreach>
    </insert>

    <!-- bind 标签测试 -->
    <select id="selectWithBind" resultMap="userResultMap">
        <bind name="namePattern" value="'%' + name + '%'"/>
        SELECT * FROM user_info
        WHERE name LIKE #{namePattern}
        ORDER BY id
    </select>

    <!-- 组合动态 SQL：where + if + foreach -->
    <select id="selectComplex" resultMap="userResultMap">
        SELECT * FROM user_info
        <where>
            <if test="name != null">
                AND name LIKE #{name}
            </if>
            <if test="ids != null">
                AND id IN
                <foreach collection="ids" item="id" open="(" separator="," close=")">
                    #{id}
                </foreach>
            </if>
        </where>
        ORDER BY id
    </select>

    <!-- choose + where 组合 -->
    <select id="selectByAgeCategory" resultMap="userResultMap">
        SELECT * FROM user_info
        <where>
            AND name LIKE 'DynSql%'
            <choose>
                <when test="category == 'young'">
                    AND age &lt; 30
                </when>
                <when test="category == 'middle'">
                    AND age BETWEEN 30 AND 40
                </when>
                <otherwise>
                    AND age &gt; 40
                </otherwise>
            </choose>
        </where>
        ORDER BY id
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/oneapi/mapper/XmlSqlFragmentMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.SqlFragmentMapper">

    <resultMap id="userResultMap" type="net.hasor.dbvisitor.test.oneapi.model.UserInfo">
        <id column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <!-- 列名片段 -->
    <sql id="baseColumns">
        id, name, age, email, create_time
    </sql>

    <!-- 条件片段（包含动态 SQL） -->
    <sql id="dynamicCondition">
        <if test="name != null">
            AND name LIKE #{name}
        </if>
        <if test="minAge != null">
            AND age &gt;= #{minAge}
        </if>
        <if test="maxAge != null">
            AND age &lt;= #{maxAge}
        </if>
    </sql>

    <!-- 排序片段 -->
    <sql id="defaultOrder">
        ORDER BY id ASC
    </sql>

    <insert id="insertUser">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, CURRENT_TIMESTAMP)
    </insert>

    <!-- 在 SELECT 列中使用 include -->
    <select id="selectWithColumnFragment" resultMap="userResultMap">
        SELECT <include refid="baseColumns"/>
        FROM user_info
        WHERE id = #{id}
    </select>

    <!-- 在 WHERE 中使用包含动态 SQL 的 include -->
    <select id="selectWithConditionFragment" resultMap="userResultMap">
        SELECT <include refid="baseColumns"/>
        FROM user_info
        WHERE 1=1
        <include refid="dynamicCondition"/>
        <include refid="defaultOrder"/>
    </select>

    <!-- 多个 include 组合使用 -->
    <select id="selectWithMultipleFragments" resultMap="userResultMap">
        SELECT <include refid="baseColumns"/>
        FROM user_info
        WHERE name LIKE 'SqlFrag%'
        <include refid="defaultOrder"/>
    </select>

    <!-- 仅使用排序片段 -->
    <select id="selectAllOrdered" resultMap="userResultMap">
        SELECT * FROM user_info
        WHERE name LIKE 'SqlFrag%'
        <include refid="defaultOrder"/>
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/XmlResultHandlerMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.ResultHandlerMapper">

    <resultMap id="userResultMap" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <insert id="insertUser">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, CURRENT_TIMESTAMP)
    </insert>

    <!-- resultType：实体类 -->
    <select id="selectByResultType" resultType="net.hasor.dbvisitor.test.model.UserInfo">
        SELECT * FROM user_info WHERE name LIKE 'ResHdl%' AND age &gt; #{minAge} ORDER BY id
    </select>

    <!-- resultType：map -->
    <select id="selectByResultTypeMap" resultType="map">
        SELECT * FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY id
    </select>

    <!-- resultType：int -->
    <select id="countByResultType" resultType="int">
        SELECT COUNT(*) FROM user_info WHERE name LIKE 'ResHdl%'
    </select>

    <!-- resultType：string -->
    <select id="selectNamesByResultType" resultType="string">
        SELECT name FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY id
    </select>

    <!-- resultMap -->
    <select id="selectByResultMap" resultMap="userResultMap">
        SELECT * FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY id
    </select>

    <!-- resultRowMapper：ColumnMapRowMapper -->
    <select id="selectByColumnMapRowMapper"
            resultRowMapper="net.hasor.dbvisitor.jdbc.mapper.ColumnMapRowMapper">
        SELECT * FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY id
    </select>

    <!-- resultSetExtractor：ColumnMapResultSetExtractor -->
    <select id="selectByColumnMapExtractor"
            resultSetExtractor="net.hasor.dbvisitor.jdbc.extractor.ColumnMapResultSetExtractor">
        SELECT * FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY id
    </select>

    <!-- resultSetExtractor：PairsResultSetExtractor -->
    <select id="selectIdNamePairs"
            resultSetExtractor="net.hasor.dbvisitor.jdbc.extractor.PairsResultSetExtractor">
        SELECT id, name FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY id
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/XmlCrudMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.CrudMapper">

    <resultMap id="simpleResultMap" type="net.hasor.dbvisitor.test.model.UserInfo">
        <result column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <!-- insert -->
    <insert id="insertUser">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, CURRENT_TIMESTAMP)
    </insert>

    <!-- select single by resultMap -->
    <select id="selectById" resultMap="simpleResultMap">
        SELECT * FROM user_info WHERE id = #{id}
    </select>

    <!-- select list by resultType entity -->
    <select id="selectAll" resultType="net.hasor.dbvisitor.test.model.UserInfo">
        SELECT * FROM user_info WHERE name LIKE 'XmlCrud%' ORDER BY id
    </select>

    <!-- select list by resultType map -->
    <select id="selectAllAsMap" resultType="map">
        SELECT * FROM user_info WHERE name LIKE 'XmlCrud%' ORDER BY id
    </select>

    <!-- select count by resultType int -->
    <select id="countAll" resultType="int">
        SELECT COUNT(*) FROM user_info WHERE name LIKE 'XmlCrud%'
    </select>

    <!-- select single column by resultType string -->
    <select id="selectNames" resultType="string">
        SELECT name FROM user_info WHERE name LIKE 'XmlCrud%' ORDER BY id
    </select>

    <!-- update -->
    <update id="updateEmail">
        UPDATE user_info SET email = #{email} WHERE id = #{id}
    </update>

    <!-- delete -->
    <delete id="deleteById">
        DELETE FROM user_info WHERE id = #{id}
    </delete>

    <!-- execute (DDL/DML) -->
    <execute id="deleteByName">
        DELETE FROM user_info WHERE name LIKE #{name}
    </execute>

    <!-- select for pagination -->
    <select id="selectForPage" resultMap="simpleResultMap">
        SELECT * FROM user_info WHERE name LIKE 'XmlCrud%' ORDER BY id
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapping/index_column_sub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.xml.indexcolsub">

    <!-- 使用 <column> 子元素方式声明索引 -->
    <entity id="IndexColSubEntity" table="user_info" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name"/>
        <mapping column="email" property="email"/>
        <index name="idx_cols_sub" unique="true" comment="index via sub elements">
            <column>name</column>
            <column>email</column>
        </index>
    </entity>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapping/keygen_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.xml.keygen">

    <!-- keyType="auto" 自增主键 -->
    <entity id="AutoKeyEntity" table="user_info_auto" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id" keyType="auto"/>
        <mapping column="name" property="name"/>
    </entity>

    <!-- keyType="uuid32" 32位UUID（无连字符） -->
    <entity id="UUID32KeyEntity" table="user_info_uuid32" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" keyType="uuid32"/>
    </entity>

    <!-- keyType="uuid36" 36位UUID（标准格式） -->
    <entity id="UUID36KeyEntity" table="user_info_uuid36" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" keyType="uuid36"/>
    </entity>

    <!-- 无 keyType → keySeqHolder 为 null -->
    <entity id="NoneKeyEntity" table="user_info_none" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name"/>
    </entity>

    <!-- 多字段不同 keyType -->
    <entity id="MappingKeyEntity" table="user_info_mapkey" type="net.hasor.dbvisitor.test.model.UserInfo">
        <id column="id" property="id" keyType="auto"/>
        <mapping column="name" property="name" keyType="uuid36"/>
        <mapping column="email" property="email" keyType="uuid32"/>
    </entity>

</mapper>
