=== zycgit/dbvisitor/hasordb-core/src/main/resources/net/hasor/db/dal/repository/mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
       Copyright 2009-2018 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.
-->
<!ELEMENT mapper ( entityMap* | resultMap* | sql* | insert* | update* | delete* | select* | callable* )+>
<!ATTLIST mapper
        namespace CDATA #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT entityMap (id*, mapping*)>
<!ATTLIST entityMap
        schema CDATA #IMPLIED
        table CDATA #REQUIRED
        type CDATA #REQUIRED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT resultMap (id*, result*)>
<!ATTLIST resultMap
        id CDATA #REQUIRED
        type CDATA #REQUIRED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT id EMPTY>
<!ATTLIST id
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        column CDATA #REQUIRED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        >

<!ELEMENT result EMPTY>
<!ATTLIST result
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        column CDATA #REQUIRED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        >

<!ELEMENT mapping EMPTY>
<!ATTLIST mapping
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        column CDATA #REQUIRED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        >

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT update (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST selectKey
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        resultMap CDATA #IMPLIED
        resultType CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType CDATA #IMPLIED
        multipleResultType CDATA #IMPLIED
        keyProperty CDATA #REQUIRED
        keyColumn CDATA #IMPLIED
        order (BEFORE|AFTER) #IMPLIED
        >

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        resultMap CDATA #IMPLIED
        resultType CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
        multipleResult (FIRST|LAST|ALL) #IMPLIED
        >

<!ELEMENT callable (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST callable
        id CDATA #REQUIRED
        timeout CDATA #IMPLIED
        resultMap CDATA #IMPLIED
        resultType CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
        multipleResult (FIRST|LAST|ALL) #IMPLIED
        resultOut CDATA #IMPLIED
        >

<!-- Dynamic -->
<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
        id CDATA #REQUIRED
        >

<!ELEMENT include EMPTY>
<!ATTLIST include
        refid CDATA #REQUIRED
        >

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
        prefix CDATA #IMPLIED
        prefixOverrides CDATA #IMPLIED
        suffix CDATA #IMPLIED
        suffixOverrides CDATA #IMPLIED
        caseSensitive (true|false) #IMPLIED
        >

<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
        collection CDATA #REQUIRED
        item CDATA #REQUIRED
        index CDATA #IMPLIED
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        separator CDATA #IMPLIED
        >

<!ELEMENT choose (when* , otherwise?)>

<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
        test CDATA #REQUIRED
        >

<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
        test CDATA #REQUIRED
        >

<!ELEMENT bind EMPTY>
<!ATTLIST bind
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        overwrite (true|false) #IMPLIED
        >

=== zycgit/dbvisitor/hasordb-core/src/test/resources/net_hasor_db/dal_dynamic/mapper_3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mapper PUBLIC "-//hasor.net//DTD Mapper 3.0//EN" "http://www.hasor.net/schema/hasordb/mapper.dtd">
<mapper namespace="net.hasor.test.db.dal.Mapper1Dal">

    <resultMap id="tb_user_resultMap" type="net.hasor.test.db.dto.TbUser2">
        <id column="user_uuid" property="uid"/>
        <result column="name" property="name"/>
        <result column="login_name" property="account"/>
        <result column="login_password" property="password"/>
        <result column="email" property="mail"/>
        <result column="index" property="index" javaType="int"/>
        <result column="register_time" property="createTime"/>
    </resultMap>

    <sql id="projectInfoDO_allColumns">
        id , owner_id
    </sql>

    <!-- dataqlMap="tb_user_dataqlMap"-->
    <select id="testBind" resultMap="tb_user_resultMap">
        SELECT
            <include refid="projectInfoDO_allColumns"/>
        FROM console_job
        WHERE aac = #{abc}
    </select>

</mapper>

=== zycgit/dbvisitor/hasordb-core/src/test/resources/net_hasor_db/dal_repository/mapper_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//hasor.net//DTD Mapper 1.0//EN" "https://www.hasor.net/schema/hasordb/mapper.dtd">
<mapper namespace="resultMap_test">
    <resultMap id="blobResourceDO" type="net.hasor.test.db.dto.TB_User" autoMapping="true">
        <id column="id" property="id"/>
        <result column="gmt_create" property="gmtCreate"/>
        <result column="gmt_modified" property="gmtModified"/>
        <result column="instance_id" property="instanceId"/>
        <result column="owner_name" property="ownerName"/>
        <result column="owner_type" property="ownerType" javaType="com.clougence.clouddm.console.web.constants.ResourceType"/>
        <result column="blob_type" property="blobType" javaType="com.clougence.clouddm.console.web.constants.SecurityFileType"/>
        <result column="content" property="content"/>
    </resultMap>

    <resultMap id="blobResourceDO" type="net.hasor.test.db.dto.TB_User" autoMapping="true">
        <id column="id" property="id"/>
        <result column="gmt_create" property="gmtCreate"/>
        <result column="gmt_modified" property="gmtModified"/>
        <result column="instance_id" property="instanceId"/>
        <result column="owner_name" property="ownerName"/>
        <result column="owner_type" property="ownerType" javaType="com.clougence.clouddm.console.web.constants.ResourceType"/>
        <result column="blob_type" property="blobType" javaType="com.clougence.clouddm.console.web.constants.SecurityFileType"/>
        <result column="content" property="content"/>
    </resultMap>
</mapper>
